
# PostgreSQL Configuration (Supabase)
# Host: db.[project-ref].supabase.co
# Port: 5432
# Database: postgres
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.fxsufmtwixqjfgfqfmxo.supabase.co:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
# IMPORTANT: This is the database password you set when creating the Supabase project
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Applefor33!}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true

# Supabase API Configuration
supabase.url=https://fxsufmtwixqjfgfqfmxo.supabase.co
supabase.key=${SUPABASE_ANON_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4c3VmbXR3aXhxamZnZnFmbXhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2NzMwMjEsImV4cCI6MjA3OTI0OTAyMX0.5dRXOTWLpbwE3M82x-10z9MaZpzFM1sq8JiuDhsO9Kc}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4c3VmbXR3aXhxamZnZnFmbXhvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MzY3MzAyMSwiZXhwIjoyMDc5MjQ5MDIxfQ.hFeQJVUdfyqlG7rBUMlRAT6bZh844gUPf1EvMym7Yy4}

#APi Keys
FSKEY=ACLsQz31NSRSYnO3FRIW5z

#
## SPRING SECURITY
#
# ...
