
# PostgreSQL Configuration (Supabase)
# Host: db.[project-ref].supabase.co
# Port: 5432
# Database: postgres
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.lqaqsssnjwouihhtxhdh.supabase.co:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
# IMPORTANT: This is the database password you set when creating the Supabase project
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Applefor33!}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true

# Supabase API Configuration
supabase.url=https://lqaqsssnjwouihhtxhdh.supabase.co
supabase.key=${SUPABASE_ANON_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxYXFzc3NuandvdWloaHR4aGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwMTg2NzUsImV4cCI6MjA3OTU5NDY3NX0.6AqgLhzDoq44ReaUKnOLLcwFSBlgiQFEQtYfstqKdpI}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxYXFzc3NuandvdWloaHR4aGRoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NDAxODY3NSwiZXhwIjoyMDc5NTk0Njc1fQ.vGGDv3QDwjPfkSfyFBgsEP7hj6A-uH8kR5UQJxnNi4c}

#APi Keys
FSKEY=ACLsQz31NSRSYnO3FRIW5z

#
## SPRING SECURITY
#
# ...
